name: Deploy Backend to Vercel to production

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main
  pull_request:
    paths:
      - 'backend/**'
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '20'  # Specify the Node.js version
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies
        working-directory: backend  # Set the working directory to the backend folder
        # run: npm install
        run: bun install  # Use the appropriate command for your project

      - name: Build the project
        working-directory: backend  # Set the working directory to the backend folder
        # run: npm run build  # Use the appropriate build command for your project
        run: bun run build  # Use the appropriate build command for your project

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        working-directory: backend  # Set the working directory to the backend folder
        run: |
          bun install -g vercel
          vercel deploy --prod --token $VERCEL_TOKEN --confirm
