name: Deploy Backend to Vercel

on:
  push:
    paths:
      - 'backend/**'  # Only trigger on changes within the backend directory
    branches:
      - develop  # Change this to your default branch if different
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend  # Set the working directory to the backend folder

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Use the appropriate build command for your project

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          vercel --prod --token $VERCEL_TOKEN --confirm
